# Generated by Django 6.1.1 on 2026-09-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
