# Generated by Django 6.1.1 on 2026-10-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0003_profile_description_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_range',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
