# Generated by Django 6.1.1 on 2026-10-04 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0004_alter_experience_date_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('date_range', models.CharField(max_length=50, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('study_description', models.CharField(max_length=100, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
